schema_version: '2.0'
package: tabak2007-dopamine
version: 1.0.0
title: Tabak2007_dopamine Lab
description: The model is encoded according to the paper Low dose of dopamine may
  stimulate prolactin secretion by increasing fast potassium currents Figure5 has
  been reproduced by MathSBML. It can be used to explore dose-response dynamics and
  compare treatment scenarios across conditions.
models:
- alias: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model
  path: models/core
  parameters:
    model_path: data/BIOMD0000000138.xml
    integration_step: 0.2
- alias: visualisation
  path: models/visualisation
wiring:
- from: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.state
  to:
  - visualisation.pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model_state
- from: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.summary
  to:
  - visualisation.pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model_summary
- from: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.species_labels
  to:
  - visualisation.pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model_species_labels
runtime:
  duration: 60.0
  communication_step: 2.0
  initial_inputs: {}
tags:
- pharmacology
- neuroscience
- pharmacodynamics
- signaling
- sbml
- tellurium
- faithful
- biomodels_ebi
io:
  inputs:
  - name: initial_calcium_concentration
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.initial_calcium_concentration
    label: Initial Calcium Concentration
  - name: calcium_conductance
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.calcium_conductance
    label: Calcium Conductance
  - name: potassium_conductance
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.potassium_conductance
    label: Potassium Conductance
  - name: sk_conductance
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.sk_conductance
    label: Sk Conductance
  - name: membrane_capacitance
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.membrane_capacitance
    label: Membrane Capacitance
  outputs:
  - name: state
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.state
    label: Tracked source state
  - name: summary
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.summary
    label: Simulation summary
  - name: species_labels
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.species_labels
    label: Observable labels
  - name: calcium_concentration
    maps_to: pharmacology_sbml_tabak2007_dopamine_biomd0000000138_model.calcium_concentration
    label: Calcium Concentration
